config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :tournaments, only: [:index]
    resources :competitors, only: [:index, :new, :create]
    resources :one_off_competitions, only: [:create, :show] do
      resources :players, only: [:create], module: :one_off_competitions
      resource :state, only: [:create, :destroy], module: :one_off_competitions
      resource :points, only: [:create], module: :one_off_competitions
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/competition.rb
class Competition < ApplicationRecord
  has_many :participations
  has_many :competitors, through: :participations

  validates :uid, presence: true, uniqueness: true
  validates :state, presence: true

  enum state: { created: 0, started: 1 }
end

app/models/competitor.rb
class Competitor < ApplicationRecord
  validates :name, presence: true

  has_many :participations
  has_many :competitions, through: :participations
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :competitor
  belongs_to :competition
end

app/controllers/admin/competitors_controller.rb
class Admin::CompetitorsController < ApplicationController
  def index
    render :index, locals: { competitors: Competitor.all }
  end

  def new
    render :new
  end

  def create
    if competitor = Competitor.create(competitor_params)
      flash.notice = "Competitor '#{competitor.name}' has been created"
      redirect_to admin_competitors_path
    else
      render :new
    end
  end

  private

  def competitor_params
    params.require(:competitor).permit(:name)
  end
end

app/controllers/admin/one_off_competitions/players_controller.rb
module Admin
  module OneOffCompetitions
    class PlayersController < ApplicationController
      include Command::Execute

      def create
        player_id = SecureRandom.uuid

        cmd = Command::AddPlayer.new(
          id: player_id,
          name: player_params.fetch(:name),
          competition_id: competition_id
        )

        execute(cmd)

        redirect_to admin_one_off_competition_path(id: competition_id)
      end

      private

      def player_params
        params.require(:competitor).permit(:name)
      end

      def competition_id
        params.permit(:one_off_competition_id).fetch(:one_off_competition_id)
      end
    end
  end
end

app/controllers/admin/one_off_competitions/points_controller.rb
module Admin
  module OneOffCompetitions
    class PointsController < ApplicationController
      include Command::Execute

      def create
        cmd = Command::AddPointsForPlayer.new(
          player_id: player_id,
          competition_id: competition_id,
          points: points
        )

        execute(cmd)

        redirect_to admin_one_off_competition_path(id: competition_id)
      end

      private

      def player_id
        params.permit(:player).fetch(:player)
      end

      def points
        params.permit(:points).fetch(:points)
      end

      def competition_id
        params.permit(:one_off_competition_id).fetch(:one_off_competition_id)
      end
    end
  end
end

app/controllers/admin/one_off_competitions/states_controller.rb
module Admin
  module OneOffCompetitions
    class StatesController < ApplicationController
      include Command::Execute

      def create
        cmd = Command::StartCompetition.new(competition_id: competition_id)

        execute(cmd)

        redirect_to admin_one_off_competition_path(id: competition_id)
      end

      def destroy
        cmd = Command::FinishCompetition.new(competition_id: competition_id)

        execute(cmd)

        redirect_to admin_one_off_competition_path(id: competition_id)
      end

      private

      def competition_id
        params.permit(:one_off_competition_id).fetch(:one_off_competition_id)
      end
    end
  end
end

app/controllers/admin/one_off_competitions_controller.rb
module Admin
  class OneOffCompetitionsController < ApplicationController
    def create
      redirect_to admin_one_off_competition_path(id: SecureRandom.uuid)
    end

    def show
      competition_id = params.fetch(:id)
      stream = "Aggregate::Competition$#{competition_id}"
      competition = Aggregate::Competition.new(competition_id).load(stream)

      render :show, locals: { competition: competition }
    end
  end
end

app/controllers/admin/tournaments_controller.rb
module Admin
  class TournamentsController < ApplicationController
    def index
      render :index
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/views/admin/competitors/index.haml
- competitors.each do |competitor|
  .competitor #{competitor.name}

app/views/admin/competitors/new.haml
.form
  = form_tag(admin_competitors_path, method: :create) do
    = label_tag(:competitor_name, 'Name')
    = text_field_tag('competitor[name]')
    = submit_tag('Create Competitor')

app/views/admin/one_off_competitions/show.haml
.row
  .col
    .form-segment
      %h1 Competition
      #state= "Competition #{competition.state}"

.row
  .col
    - unless competition.players.size.zero?
      .players-list.rounded.border
        .form-segment
          %h3 Players
          %ol
            - competition.players.each do |player|
              %li#score= "#{player.name}: #{pluralize(player.points, 'point')}"

    - unless competition.started? || competition.finished?
      #add-player.form.form-segment
        = form_tag(admin_one_off_competition_players_path(competition.id), method: :create) do
          .input-group
            = text_field_tag('competitor[name]', nil, class: 'form-control', placeholder: 'Name')
            .input-group-btn
              = submit_tag('Add Player', class: 'btn btn-secondary')

    - if competition.created? && competition.players.any?
      .form-segment
        = button_to 'Start Competition', admin_one_off_competition_state_path(competition.id), method: :post, class: 'btn btn-primary'

    - if competition.started?
      .players-list.rounded.border
        #add-points.form.form-segment
          = form_tag(admin_one_off_competition_points_path(competition.id), method: :create) do
            .input-group
              .input-group-btn
                = submit_tag('Add', class: 'btn btn-secondary')
              = select_tag(:player, options_from_collection_for_select(competition.players, :id, :name), class: 'form-control')
              = text_field_tag('points', nil, class: 'form-control', placeholder: 'points')

      .form-segment
        = button_to 'Finish Competition', admin_one_off_competition_state_path(competition.id), method: :delete, class: 'btn btn-primary'

    .form-segment
      - if competition.finished?
        #winner= "#{competition.winning_player.name} wins"
        - if competition.players.size == 2
          - first = competition.players_sorted_by_points.first
          - second = competition.players_sorted_by_points.last
          #final-score= "#{first.name} #{first.points} - #{second.points} #{second.name}"

  .col

app/views/admin/teams/new.haml
.form
  = form_tag(admin_teams_path, method: :create) do
    = label_tag(:name)
    = text_field_tag(:name)
    = submit_tag('Create Team')

app/views/admin/tournaments/index.haml
%h1 Welcome!
= button_to 'Create One-off Competition', action: :create, controller: 'one_off_competitions'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Tournament"
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %nav.navbar.navbar-light.bg-light
      .container
        %a.navbar-brand(href="#") Tournament

    .container
      - if flash[:notice]
        .row
          .col
            .notice= flash[:notice]
      = yield